[book]
authors = ["Gabor Szabo"]
#text-direction = "rtl"
language = "he"
src = "src"
title = "מביני קוד - מביני פייתון"
# description =


# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/python-he.code-maven.com"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/szabgab/python-he.code-maven.com/edit/main/{path}"

# Remove the printer icon from the menu
[output.html.print]
enable = false

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"

